### ISSUE TITLE
ansible plugin fails with FileNotFoundError

### ISSUE THREAD

**Issue by stapelberg** [larswirzenius/vmdb2#14]
```
% git describe
vmdb2-0.8-32-gaf846b2
% sudo ./vmdb2 --output ../raspi3.img ../raspi3.yaml --log ../raspi3.log
[…]
2017-09-21 23:04:17 DEBUG STDOUT: b'Setting up ansible (2.2.1.0-2) ...\n'
2017-09-21 23:04:23 DEBUG STDOUT: b'Processing triggers for ca-certificates (20161130+nmu1) ...\n'
2017-09-21 23:04:23 DEBUG STDOUT: b'Updating certificates in /etc/ssl/certs...\n'
2017-09-21 23:04:31 DEBUG STDOUT: b'0 added, 0 removed; done.\n'
2017-09-21 23:04:31 DEBUG STDOUT: b'Running hooks in /etc/ca-certificates/update.d...\n'
2017-09-21 23:04:31 DEBUG STDOUT: b'done.\n'
2017-09-21 23:04:31 INFO Running step: {'ansible': 'root-fs', 'playbook': 'ansible.yml'}
2017-09-21 23:04:31 INFO Running ansible playbook ansible.yml on filesystem at /tmp/tmpr6h53bhd (root-fs)
2017-09-21 23:04:31 INFO Created /tmp/tmpdmf7v962 for Ansible inventory
2017-09-21 23:04:31 INFO Exec: ['ansible-playbook', '-c', 'chroot', '-i', '/tmp/tmpdmf7v962', 'ansible.yml']
2017-09-21 23:04:31 DEBUG run external command: [['ansible-playbook', '-c', 'chroot', '-i', '/tmp/tmpdmf7v962', 'ansible.yml']]
2017-09-21 23:04:31 ERROR [Errno 2] No such file or directory: 'ansible-playbook': 'ansible-playbook'
Traceback (most recent call last):
  File "/home/michael/2017-09-19-raspi3-vmdb2/vmdb2/vmdb/app.py", line 96, in run_steps_helper
    method(expanded_step, self.settings, state)
  File "/home/michael/2017-09-19-raspi3-vmdb2/vmdb2/vmdb/plugins/ansible_plugin.py", line 57, in run
    env=env)
  File "/home/michael/2017-09-19-raspi3-vmdb2/vmdb2/vmdb/runcmd.py", line 53, in runcmd
    return cliapp.runcmd(argv, *argvs, **kwargs)
  File "/usr/lib/python3/dist-packages/cliapp/runcmd.py", line 55, in runcmd
    exit_code, out, err = runcmd_unchecked(argv, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/cliapp/runcmd.py", line 114, in runcmd_unchecked
    raise e
  File "/usr/lib/python3/dist-packages/cliapp/runcmd.py", line 106, in runcmd_unchecked
    kwargs)
  File "/usr/lib/python3/dist-packages/cliapp/runcmd.py", line 143, in _build_pipeline
    stderr=stderr, close_fds=True, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1289, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ansible-playbook': 'ansible-playbook'
2017-09-21 23:04:31 INFO Something went wrong, cleaning up!
```

I added the following to raspi3.yaml, but get the same failure:
```
- apt: ansible
   fs-tag: root-fs
```

**Comment by larswirzenius** [comment]
Does the system you run vmdb2 on have ansible installed?

**Comment by stapelberg** [comment]
Sorry, forgot to follow up here.

> Does the system you run vmdb2 on have ansible installed?

It didn’t at the time. Installing ansible on the host, and python in the image, indeed fixed the issue.

Perhaps we could make the error message a little more descriptive?

**Comment by larswirzenius** [comment]
Sure, patch to make a better error message is welcome.
