### ISSUE TITLE
recent apt change breaks image building

### ISSUE THREAD

**Issue by stapelberg** [larswirzenius/vmdb2#23]
Since commit https://github.com/larswirzenius/vmdb2/commit/3d4f5713bba3bd453b9815cbf4317d12b1448534, with the following yaml:

```yaml
  - apt: install
    packages:
    - ssh
    - dosfstools
    # Contains /lib/firmware/brcm/brcmfmac43430-sdio.bin (required for WiFi).
    - firmware-brcm80211
    - wireless-tools
    - wpasupplicant
    fs-tag: root-fs
```

…I get:
```
2017-10-07 15:14:55 INFO Running step: {'fs-tag': 'root-fs', 'apt': 'install', 'packages': ['ssh', 'dosfstools', 'firmware-brcm80211', 'wireless-tools', 'wpasupplicant']}
2017-10-07 15:14:55 ERROR 'AptStepRunner' object has no attribute 'install_package'
Traceback (most recent call last):
  File "/home/michael/2017-09-19-raspi3-vmdb2/vmdb2/vmdb/app.py", line 95, in run_steps_helper
    method(step, self.settings, state)
  File "/home/michael/2017-09-19-raspi3-vmdb2/vmdb2/vmdb/plugins/apt_plugin.py", line 48, in run
    self.install_package(mount_point, [], 'eatmydata')
AttributeError: 'AptStepRunner' object has no attribute 'install_package'
```

Changing the `install_package` to `install_packages`, I get:
```
2017-10-07 15:34:42 INFO Exec: ['chroot', '/tmp/tmph1s85f57', 'eatmydata', 'apt-get', '-y', '--no-show-progress', 'install', ['ssh', 'dosfstools', 'firmware-brcm80211', 'wireless-tools', 'wpasupplicant']]
2017-10-07 15:34:42 DEBUG run external command: [['chroot', '/tmp/tmph1s85f57', 'eatmydata', 'apt-get', '-y', '--no-show-progress', 'install', ['ssh', 'dosfstools', 'firmware-brcm80211', 'wireless-tools', 'wpasupplicant']]]
2017-10-07 15:34:42 ERROR Can't convert 'list' object to str implicitly
Traceback (most recent call last):
  File "/home/michael/2017-09-19-raspi3-vmdb2/vmdb2/vmdb/app.py", line 95, in run_steps_helper
    method(step, self.settings, state)
  File "/home/michael/2017-09-19-raspi3-vmdb2/vmdb2/vmdb/plugins/apt_plugin.py", line 50, in run
    self.install_packages(mount_point, ['eatmydata'], packages)
  File "/home/michael/2017-09-19-raspi3-vmdb2/vmdb2/vmdb/plugins/apt_plugin.py", line 63, in install_packages
    env=env)
  File "/home/michael/2017-09-19-raspi3-vmdb2/vmdb2/vmdb/runcmd.py", line 58, in runcmd_chroot
    return runcmd(full_argv, *argvs, **kwargs)
  File "/home/michael/2017-09-19-raspi3-vmdb2/vmdb2/vmdb/runcmd.py", line 53, in runcmd
    return cliapp.runcmd(argv, *argvs, **kwargs)
  File "/usr/lib/python3/dist-packages/cliapp/runcmd.py", line 55, in runcmd
    exit_code, out, err = runcmd_unchecked(argv, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/cliapp/runcmd.py", line 106, in runcmd_unchecked
    kwargs)
  File "/usr/lib/python3/dist-packages/cliapp/runcmd.py", line 143, in _build_pipeline
    stderr=stderr, close_fds=True, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1228, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: Can't convert 'list' object to str implicitly
```

**Comment by larswirzenius** [comment]
Confirmed, I see the same thing. I should add building a real image to my CI when I get time to do it right.

**Comment by larswirzenius** [comment]
Fix is impending.

**Comment by larswirzenius** [comment]
Fixed now.
