### ISSUE TITLE
README: lists python2 Debian package names, not python3 Debian package names

### ISSUE THREAD

**Issue by stapelberg** [larswirzenius/vmdb2#3]
```
% ./vmdb2
Traceback (most recent call last):
  File "./vmdb2", line 3, in <module>
    import vmdb
  File "/home/michael/2017-09-19-raspi3-vmdb2/vmdb2/vmdb/__init__.py", line 21, in <module>
    from .step_list import (
  File "/home/michael/2017-09-19-raspi3-vmdb2/vmdb2/vmdb/step_list.py", line 19, in <module>
    import cliapp
ImportError: No module named 'cliapp'
% sudo apt install python3-cliapp
% ./vmdb2 --help
Usage: vmdb2 [options]
[…]
```

**Comment by larswirzenius** [comment]
thanks. Fixed now.
